name: Binder
on: [push]

jobs:
  build-docker-image:
    runs-on: ubuntu-latest
    steps:
      - name: update jupyter dependencies with repo2docker
        uses: jupyterhub/repo2docker-action@master
        with:
          DOCKER_REGISTRY: ghcr.io
          DOCKER_USERNAME: ${{ github.actor }}
          DOCKER_PASSWORD: ${{ secrets.GITHUB_TOKEN }}
          BINDER_CACHE: true
          PUBLIC_REGISTRY_CHECK: true
